import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { AuthProvider } from "@/lib/auth-context";
import GlobalLoginModal from "@/components/auth/global-login-modal";
import { NotesRefreshProvider } from "@/components/providers/notes-refresh-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <AuthProvider>
          <NotesRefreshProvider>
            <Navbar />
            {children}
            <GlobalLoginModal />
          </NotesRefreshProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
